// Bảng mệnh ngũ hành theo Can Chi
export const canChiMenh = {
  Can: [
    "Canh",
    "Tân",
    "Nhâm",
    "Quý",
    "Giáp",
    "Ất",
    "Bính",
    "Đinh",
    "Mậu",
    "Kỷ",
  ],
  Chi: [
    "Thân",
    "Dậu",
    "Tuất",
    "Hợi",
    "Tý",
    "Sửu",
    "Dần",
    "Mão",
    "Thìn",
    "Tỵ",
    "Ngọ",
    "Mùi",
  ],
  Menh: {
    "Giáp Tý": "Kim",
    "Ất Sửu": "Kim",
    "Bính Dần": "Hỏa",
    "Đinh Mão": "Hỏa",
    "Mậu Thìn": "Mộc",
    "Kỷ Tỵ": "Mộc",
    "Canh Ngọ": "Thổ",
    "Tân Mùi": "Thổ",
    "Nhâm Thân": "Kim",
    "Quý Dậu": "Kim",
    "Giáp Tuất": "Hỏa",
    "Ất Hợi": "Hỏa",
    "Bính Tý": "Thủy",
    "Đinh Sửu": "Thủy",
    "Mậu Dần": "Thổ",
    "Kỷ Mão": "Thổ",
    "Canh Thìn": "Kim",
    "Tân Tỵ": "Kim",
    "Nhâm Ngọ": "Mộc",
    "Quý Mùi": "Mộc",
    "Giáp Thân": "Thủy",
    "Ất Dậu": "Thủy",
    "Bính Tuất": "Thổ",
    "Đinh Hợi": "Thổ",
    "Mậu Tý": "Hỏa",
    "Kỷ Sửu": "Hỏa",
    "Canh Dần": "Mộc",
    "Tân Mão": "Mộc",
    "Nhâm Thìn": "Thủy",
    "Quý Tỵ": "Thủy",
    "Giáp Ngọ": "Kim",
    "Ất Mùi": "Kim",
    "Bính Thân": "Hỏa",
    "Đinh Dậu": "Hỏa",
    "Mậu Tuất": "Mộc",
    "Kỷ Hợi": "Mộc",
    "Canh Tý": "Thổ",
    "Tân Sửu": "Thổ",
    "Nhâm Dần": "Kim",
    "Quý Mão": "Kim",
    "Giáp Thìn": "Hỏa",
    "Ất Tỵ": "Hỏa",
    "Bính Ngọ": "Thủy",
    "Đinh Mùi": "Thủy",
    "Mậu Thân": "Thổ",
    "Kỷ Dậu": "Thổ",
    "Canh Tuất": "Kim",
    "Tân Hợi": "Kim",
    "Nhâm Tý": "Mộc",
    "Quý Sửu": "Mộc",
    "Giáp Dần": "Thủy",
    "Ất Mão": "Thủy",
    "Bính Thìn": "Thổ",
    "Đinh Tỵ": "Thổ",
    "Mậu Ngọ": "Hỏa",
    "Kỷ Mùi": "Hỏa",
    "Canh Thân": "Mộc",
    "Tân Dậu": "Mộc",
    "Nhâm Tuất": "Thủy",
    "Quý Hợi": "Thủy",
  },
};

// Gợi ý cá Koi và hồ theo mệnh
export const suggestionsByMenh = {
  Kim: {
    fish: ["trắng", "bạc", "vàng kim"],
    pondShape: ["hình tròn", "bầu dục"],
    pondDirection: ["Tây", "Tây Bắc"],
    number: ["4", "9"],
    location: ["Trung tâm", "Hướng Tây Bắc"],
  },
  Mộc: {
    fish: ["xanh lá cây", "đen"],
    pondShape: ["hình chữ nhật", "dài"],
    pondDirection: ["Đông", "Đông Nam"],
    number: ["3", "8"],
    location: ["Hướng Đông", "Đông Nam"],
  },
  Thủy: {
    fish: ["đen", "xanh dương"],
    pondShape: ["hình tròn", "cong uốn lượn"],
    pondDirection: ["Bắc"],
    number: ["1", "6"],
    location: ["Hướng Bắc"],
  },
  Hỏa: {
    fish: ["đỏ", "cam"],
    pondShape: ["hình tam giác"],
    pondDirection: ["Nam"],
    number: ["2", "7"],
    location: ["Hướng Nam"],
  },
  Thổ: {
    fish: ["vàng", "nâu", "cam đất"],
    pondShape: ["hình vuông"],
    pondDirection: ["Tây Nam", "Đông Bắc"],
    number: ["5", "10"],
    location: ["Tây Nam", "Đông Bắc"],
  },
};
