export const SCREEN = {
  HOME: "home",
  LOOKUP: "lookup",
  CHECK_SUIT: "check-suitability",
  PROFILE: "profile",
  EDIT_PROFILE: "edit-profile",
  NOTIFICATION_SCREEN: "notification-screen",
  POND_SCREEN: "pond-screen",
  SOCIAL_SCREEN: "social-screen",
  FENGSHUI_SCREEN: "fengshui-screen",
  POST_SCREEN: "post-screen",
  POND_DETAIL: "pond-detail",
  POND_LAYOUT: "pond-layout",
  PACKAGE_SCREEN: "package-screen",
};
